Repository dnd-side-project/dnd-10th-3-frontend, pull requests merged in 2024-02, with the labels that each got.

#56 [FEAT] 테스트 시작 UI 구현
  src/app/globals.css
  src/app/test/layout.tsx
  src/app/test/page.tsx
  src/assets/images/logo.png
  src/assets/images/test-worry.png
  src/components/common/input/Input.tsx
Labels: 🎨 Html&css

#60 [FEAT] Icon 컴포넌트, 스토리북
  src/components/common/button/Button.stories.tsx
  src/components/common/button/Button.tsx
  src/components/common/button/types.ts
  src/components/common/icon/Icon.stories.tsx
  src/components/common/icon/Icon.tsx
  src/components/common/icon/assets/ChevronLeft.tsx
  src/components/common/icon/assets/FilledHeart.tsx
  src/components/common/icon/assets/Heart.tsx
  src/components/common/icon/assets/Kakaotalk.tsx
  src/components/common/icon/assets/Profile.tsx
  src/components/common/icon/assets/Reply.tsx
  src/components/common/icon/assets/Search.tsx
  src/components/common/icon/assets/Submit.tsx
  src/components/common/icon/assets/User.tsx
  src/components/common/icon/assets/Votebox.tsx
  src/components/common/icon/assets/index.ts
  src/components/common/icon/index.ts
Labels: ✨ Feature, 🎨 Html&css

#65 [FEAT] Button 컴포넌트에 `empty` variant 추가
  src/components/common/button/Button.stories.tsx
  src/components/common/button/Button.tsx
  src/components/common/button/variant.tsx
Labels: 🎨 Html&css

#63 [FEAT] Header 컴포넌트, 스토리북
  src/components/common/icon/assets/Settings.tsx
  src/components/common/icon/assets/index.ts
  src/components/layout/header/Header.stories.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/components/Previous.tsx
  src/components/layout/header/components/Tab.tsx
  src/components/layout/header/components/index.ts
  src/components/layout/header/index.ts
  src/constants/.gitkeep
  src/constants/tab.ts
  styles/theme/spacing.ts
Labels: ✨ Feature, 🎨 Html&css

#59 [FEAT] 로그인 페이지 UI
  src/app/login/page.tsx
  src/components/AuthButton/KakaoLoginButton.tsx
  src/components/AuthButton/index.ts
  src/components/layout/header/Header.tsx
  styles/theme/colors.ts
Labels: 🎨 Html&css

#72 [FEAT] 아이콘 추가
  src/components/common/icon/assets/Check.tsx
  src/components/common/icon/assets/ChevronRight.tsx
  src/components/common/icon/assets/Clock.tsx
  src/components/common/icon/assets/Link.tsx
  src/components/common/icon/assets/More.tsx
  src/components/common/icon/assets/Photo.tsx
  src/components/common/icon/assets/Remove.tsx
  src/components/common/icon/assets/X.tsx
  src/components/common/icon/assets/index.ts
Labels: ✨ Feature, 🎨 Html&css

#73 [FEAT] 커뮤니티 (투표하기) 기본적인 UI 구현
  src/app/globals.css
  src/app/layout.tsx
  src/app/test/layout.tsx
  src/app/test/page.tsx
  src/app/testing/components/FormLayout.tsx
  src/app/testing/layout.tsx
  src/app/testing/page.tsx
  src/app/vote/_component/VoteCard.tsx
  src/app/vote/_component/VoteHeader.tsx
  src/app/vote/_component/VoteLayout.tsx
  src/app/vote/page.tsx
  src/assets/images/error-worry.png
  src/components/common/icon/Icon.tsx
  src/components/common/icon/assets/Add.tsx
  src/components/common/icon/assets/index.ts
  src/components/common/input/Input.stories.tsx
  src/components/common/input/Input.tsx
  src/components/common/input/types.ts
  src/components/common/input/variant.tsx
  src/components/common/tabs/Tabs.stories.tsx
  src/components/common/tabs/Tabs.tsx
  src/components/common/tabs/index.ts
  src/components/common/tabs/tab/Tab.stories.tsx
  src/components/common/tabs/tab/Tab.tsx
  src/components/common/tabs/tab/index.ts
  src/components/layout/errors/EmptyVoteLayout.stories.tsx
  src/components/layout/errors/EmptyVoteLayout.tsx
  src/components/layout/errors/index.ts
  styles/theme/borderRadius.ts
  styles/theme/spacing.ts
Labels: ✨ Feature, 🎨 Html&css

#78 [BUGFIX] react-spring-bottm-sheet 에러 해결
  package.json
  yarn.lock
Labels: 🐞 Bug fix

#68 [FEAT] 헤더 디자인 변경
  src/components/common/icon/Icon.tsx
  src/components/common/icon/assets/User.tsx
  src/components/layout/header/Header.stories.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/components/Tab.tsx
  styles/theme/colors.ts
Labels: 🎨 Html&css

#80 [BUGFIX] header 수정 후 사이드 이팩트 해결
  src/app/vote/_component/VoteHeader.tsx
  src/components/layout/header/Header.tsx
Labels: 🐞 Bug fix

#75 [FEAT] VoteItem 컴포넌트, 스토리북
  src/components/common/button/Button.tsx
  src/components/common/button/types.ts
  src/components/common/radio/Radio.stories.tsx
  src/components/common/radio/Radio.tsx
  src/components/common/radio/Radio.variant.tsx
  src/components/common/radio/index.ts
  src/components/features/vote/voteItem/VoteItem.stories.tsx
  src/components/features/vote/voteItem/VoteItem.tsx
  src/components/features/vote/voteItem/VoteItem.variant.ts
  src/components/features/vote/voteItem/components/IconButton.tsx
  src/components/features/vote/voteItem/components/Image.tsx
  src/components/features/vote/voteItem/components/Input.tsx
  src/components/features/vote/voteItem/components/Progress.tsx
  src/components/features/vote/voteItem/components/Span.tsx
  src/components/features/vote/voteItem/components/index.ts
  src/components/features/vote/voteItem/index.ts
  src/types/util.ts
  styles/theme/boxShadow.ts
Labels: ✨ Feature, 🎨 Html&css

#79 [DESIGN] 디자인 피드백 반영하여 변경된 디자인 작업
  src/app/test/page.tsx
  src/app/testing/page.tsx
  src/app/vote/page.tsx
  src/components/common/button/variant.tsx
  src/components/common/input/variant.tsx
Labels: 🎨 Html&css

#84 [DESIGN] 버튼, 라디오 버튼 색깔 변경
  src/components/common/button/Button.tsx
  src/components/common/button/Button.variant.tsx
  src/components/common/radio/Radio.variant.tsx
  styles/theme/boxShadow.ts
Labels: 🎨 Html&css

#88 [DESIGN] 디자인 변경 사항에 따른 Gradient 배경 수정
  tailwind.config.ts
Labels: 🎨 Html&css

#89 [HOTFIX] vercel 배포시 에러 해결
  src/components/common/input/Input.stories.tsx
Labels: 🐞 Bug fix

#90 [BUGFIX] mypage 아이콘의 svg 어트리뷰트 camel case로 fix
  src/components/common/icon/assets/Mypage.tsx
Labels: 🐞 Bug fix

#92 [DESIGN] Divider, Textarea 디자인 수정
  src/components/common/divider/Divider.stories.tsx
  src/components/common/divider/Divider.tsx
  src/components/common/divider/Divider.variant.ts
  src/components/common/divider/variant.tsx
  src/components/common/textarea/Textarea.stories.tsx
  src/components/common/textarea/Textarea.tsx
  src/components/common/textarea/index.ts
Labels: 🎨 Html&css

#97 [DESIGN] 불필요한 색상 제거
  styles/theme/colors.ts
Labels: 🎨 Html&css

#93 [FEAT] 투표 작성하기 페이지 UI 작업
  src/app/vote/create/_components/CategorySelector.tsx
  src/app/vote/create/_components/CreateVoteForm.tsx
  src/app/vote/create/_components/VoteDateForm.tsx
  src/app/vote/create/_components/VoteForm.tsx
  src/app/vote/create/_components/index.ts
  src/app/vote/create/page.tsx
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/features/vote/voteItem/components/Input.tsx
  src/components/shared/index.ts
  src/components/shared/letterCounter/LetterCounter.tsx
  src/components/shared/optionButton/OptionButton.tsx
  src/constants/category.ts
Labels: ✨ Feature, 🎨 Html&css

#101 [FEAT] Toast 컴포넌트, 스토리북
  src/app/layout.tsx
  src/components/common/icon/assets/Confirm.tsx
  src/components/common/icon/assets/Warning.tsx
  src/components/common/icon/assets/index.ts
  src/components/common/toast/Toast.stories.tsx
  src/components/common/toast/Toast.tsx
  src/components/common/toast/Toast.variant.ts
  src/components/common/toast/ToastContainer.tsx
  src/components/common/toast/index.ts
  src/constants/toast.ts
  src/contexts/Providers.tsx
  src/contexts/toast/ToastProvider.tsx
  src/hooks/index.ts
  src/hooks/useToast.tsx
  tsconfig.json
Labels: ✨ Feature

#105 [FEAT] 투표 만들기 폼 (이미지 업로드 기능 제외)
  package.json
  src/app/vote/create/_components/CategorySelector.tsx
  src/app/vote/create/_components/CreateVoteForm.tsx
  src/app/vote/create/_components/TitleInput.tsx
  src/app/vote/create/_components/VoteForm.tsx
  src/app/vote/create/_components/index.ts
  src/components/common/button/Button.tsx
  src/components/common/button/Button.variant.tsx
  src/components/common/toast/Toast.stories.tsx
  src/components/features/vote/voteItem/components/Image.tsx
  src/components/features/vote/voteItem/components/Input.tsx
  src/components/shared/charCounter/CharCounter.tsx
  src/components/shared/index.ts
  src/components/shared/letterCounter/LetterCounter.tsx
  src/constants/toast.ts
  src/hooks/useToast.tsx
  src/schema/CreateVoteSchema.ts
  yarn.lock
Labels: ✨ Feature

#103 [FEAT] VoteCard 컴포넌트, 스토리북
  src/app/vote/_component/VoteCard.tsx
  src/app/vote/_component/VoteHeader.tsx
  src/app/vote/page.tsx
  src/components/common/avatar/Avatar.tsx
  src/components/common/icon/assets/Divider.tsx
  src/components/common/icon/assets/Reply.tsx
  src/components/common/icon/assets/index.ts
  src/components/common/tabs/Tabs.tsx
  src/components/common/tag/Tag.stories.tsx
  src/components/common/tag/Tag.tsx
  src/components/common/tag/variant.tsx
  src/components/features/vote/index.ts
  src/components/features/vote/voteCard/VoteCard.stories.tsx
  src/components/features/vote/voteCard/VoteCard.tsx
  src/components/features/vote/voteCard/components/Description.tsx
  src/components/features/vote/voteCard/components/Footer.tsx
  src/components/features/vote/voteCard/components/Header.tsx
  src/components/features/vote/voteCard/components/SubmitButton.tsx
  src/components/features/vote/voteCard/components/VoteItemGroup.tsx
  src/components/features/vote/voteCard/components/index.ts
  src/components/features/vote/voteCard/index.ts
  src/components/features/vote/voteCard/variants.ts
  src/components/features/vote/voteItem/index.ts
Labels: ✨ Feature

#112 [DESIGN] 마이페이지 UI 작업, Tabs 컴포넌트 리팩토링
  src/app/login/page.tsx
  src/app/my-page/_components/.gitkeep
  src/app/my-page/page.tsx
  src/app/mypage/_components/MyTest.tsx
  src/app/mypage/_components/MyVote.tsx
  src/app/mypage/_components/Profile.tsx
  src/app/mypage/_components/index.ts
  src/app/mypage/info/_components/NicknameForm.tsx
  src/app/mypage/info/_components/index.ts
  src/app/mypage/info/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/app/mypage/settings/page.tsx
  src/app/test/_components/TestForm.tsx
  src/app/vote/_component/VoteHeader.tsx
  src/app/vote/page.tsx
  src/components/common/icon/assets/Profile.tsx
  src/components/common/tabs/Tabs.stories.tsx
  src/components/common/tabs/Tabs.tsx
  src/components/common/tabs/tab/Tab.stories.tsx
  src/components/common/tabs/tab/Tab.tsx
  src/components/common/tabs/tab/index.ts
  src/components/features/vote/voteCard/components/Header.tsx
  src/components/layout/errors/EmptyLayout.tsx
  src/components/layout/errors/EmptyVoteLayout.stories.tsx
  src/components/layout/errors/EmptyVoteLayout.tsx
  src/components/layout/errors/index.ts
  src/components/layout/header/Header.stories.tsx
  src/components/layout/header/Header.tsx
  src/components/shared/emptyTest/EmptyTest.tsx
  src/components/shared/emptyVote/EmptyVote.tsx
  src/components/shared/index.ts
  src/constants/category.ts
  src/schema/NicknameSchema.ts
Labels: 🔨 Refactor, 🎨 Html&css

#115 [DESIGN] test 시작 페이지 레이아웃, 디자인 수정
  src/app/test/_components/TestForm.tsx
Labels: 🎨 Html&css

#110 [DESIGN] VoteItem 디자인 수정
  src/components/features/vote/voteCard/VoteCard.stories.tsx
  src/components/features/vote/voteItem/VoteItem.stories.tsx
  src/components/features/vote/voteItem/VoteItem.tsx
  src/components/features/vote/voteItem/VoteItem.variant.ts
  src/components/features/vote/voteItem/components/Image.tsx
  src/components/features/vote/voteItem/components/Img.tsx
  src/components/features/vote/voteItem/components/Input.tsx
  src/components/features/vote/voteItem/components/Span.tsx
  src/components/features/vote/voteItem/components/Text.tsx
  src/components/features/vote/voteItem/components/index.ts
  src/contexts/reactHookForm/TestFormProvider.tsx
Labels: 🎨 Html&css

#69 [FEAT] 카카오톡 소셜 로그인(회원가입) 및 로그아웃
  src/app/api/v1/login/oauth2/code/kakao/route.ts
  src/app/api/v1/logout/route.ts
  src/app/login/oauth2/code/kakao/_components/KakaoLogin.tsx
  src/app/login/oauth2/code/kakao/page.tsx
  src/app/login/page.tsx
  src/app/my-page/_components/Logout.tsx
  src/components/AuthButton/KakaoLoginButton.tsx
  src/components/AuthButton/index.ts
  src/components/shared/index.ts
  src/components/shared/kakaoLoginButton/KakaoLoginButton.tsx
  src/constants/auth.ts
  src/hooks/api/auth/useAuth.tsx
  src/lib/axios.ts
  src/lib/env.ts
  src/middleware.ts
  src/utils/auth.ts
Labels: ✨ Feature

#117 [DESIGN] 테스트 결과 UI 구현
  src/app/test/_components/TestQuestionTemplate.tsx
  src/app/test/result/_components/ResultContents.tsx
  src/app/test/result/_components/TempertaureBox.tsx
  src/app/test/result/_components/index.ts
  src/app/test/result/page.tsx
  src/app/vote/page.tsx
  src/assets/images/resultType.png
  src/assets/images/tempSVG.svg
  src/components/common/button/Button.tsx
  src/components/common/button/types.ts
  src/components/common/icon/assets/CaretUp.tsx
  src/components/common/icon/assets/index.ts
  src/components/common/progressBar/ProgressBar.tsx
  src/components/features/vote/voteItem/components/Image.tsx
  src/components/shared/index.ts
  src/constants/test/progress.ts
Labels: 🎨 Html&css

#119 [BUGFIX] 토글 동작 이상 해결 (pathname과 토글 연결)
  src/app/mypage/page.tsx
  src/app/test/_components/TestForm.tsx
  src/app/vote/_component/VoteHeader.tsx
  src/components/common/tabs/Tabs.stories.tsx
  src/components/layout/header/Header.stories.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/components/Previous.tsx
  src/components/layout/header/components/Tab.tsx
  src/components/layout/header/components/ToggleNav.tsx
  src/components/layout/header/components/index.ts
  src/constants/category.ts
  src/constants/mypage.ts
  src/constants/tab.ts
  src/constants/toggleNav.ts
Labels: 🐞 Bug fix, 🔨 Refactor

#118 [FEAT] 투표 만들기 폼에 이미지 첨부 기능
  src/app/vote/create/_components/CreateVoteForm.tsx
  src/app/vote/create/_components/VoteForm.tsx
  src/app/vote/create/_components/VoteItemImgForm.tsx
  src/app/vote/create/_components/index.ts
  src/components/shared/imgUploadButton/ImageUploadButton.tsx
  src/components/shared/index.ts
  src/constants/toast.ts
  src/hooks/index.ts
  src/hooks/useImageUpload.ts
  src/schema/CreateVoteSchema.ts
Labels: ✨ Feature

#123 [FEAT] 테스트 시작 페이지 기본 유효성 검사 로직 구현
  src/app/test/_components/TestForm.tsx
  src/app/test/_components/TestQuestionTemplate.tsx
  src/app/test/result/_components/TempertaureBox.tsx
  src/components/common/progressBar/ProgressBar.tsx
Labels: ✨ Feature

#125 [FEAT] 테스트 진행 완료 후 로딩 UI 구현
  src/app/test/_components/TestForm.tsx
  src/app/test/_components/TestLoading.tsx
  src/components/common/progressBar/ProgressBar.tsx
  src/components/features/test/loading/Loading.tsx
  src/constants/test/step.tsx
  src/hooks/useTimeout.ts
Labels: ✨ Feature

#128 [BUGFIX] useSearchParams 관련 배포 이슈 해결
  src/app/login/oauth2/code/kakao/page.tsx
  src/app/vote/_component/VoteHeader.tsx
  src/components/common/tabs/Tabs.stories.tsx
Labels: 🐞 Bug fix

#129 [BUGFIX] 로그인 문구 파싱 중 undefined 에러
  src/app/login/page.tsx
  src/app/my-page/_components/Logout.tsx
  src/middleware.ts
Labels: 🐞 Bug fix

#133 [DESIGN] 테스트 및 커뮤니티 변경된 디자인 반영
  src/app/test/_components/TestQuestionTemplate.tsx
  src/app/vote/_component/VoteLayout.tsx
  src/app/vote/page.tsx
  src/components/common/input/variant.tsx
  src/constants/test/step.tsx
Labels: 🎨 Html&css

#136 [DESIGN] 버튼 accent 버라이언트 추가
  src/app/test/_components/TestQuestionTemplate.tsx
  src/app/vote/page.tsx
  src/components/common/button/Button.stories.tsx
  src/components/common/button/Button.tsx
  src/components/common/button/Button.variant.tsx
  src/components/common/button/types.ts
  tailwind.config.ts
Labels: 🎨 Html&css

#140 [FEAT] auth mutation 작성
  next.config.mjs
  src/app/login/oauth2/code/kakao/_components/KakaoLogin.tsx
  src/constants/toast.ts
  src/hooks/api/auth/index.ts
  src/hooks/api/auth/useAuth.tsx
  src/hooks/api/auth/useAuth/types.ts
  src/hooks/api/auth/useAuth/useAuth.tsx
  src/types/response.ts
Labels: ✨ Feature

#142 [CHORE] 쿠키 value 상수 변경
  src/constants/auth.ts
  src/lib/env.ts
Labels: 🔨 Refactor

#134 [FEAT] 테스트 결과 두가지 공유 기능 구현
  public/images/worry.png
  src/app/layout.tsx
  src/app/test/_components/TestLoading.tsx
  src/app/test/result/_components/KakaoScript.tsx
  src/app/test/result/_components/ResultContents.tsx
  src/app/test/result/_components/ShareBox.tsx
  src/app/test/result/_components/index.ts
  src/app/test/result/layout.tsx
  src/components/shared/index.ts
  src/components/shared/kakaoShareButton/KakaoShareButton.tsx
  src/config.ts
  src/constants/metadata.ts
  src/utils/share.ts
Labels: ✨ Feature

#146 [BUGFIX] SVG 파일 속성 camelCase로 변경하여 에러 해결
  src/app/layout.tsx
  src/assets/images/charater.svg
  src/assets/images/testWorrySVG.svg
  src/components/common/spinner/Spinner.tsx
Labels: 🐞 Bug fix

#148 [BUGFIX] 로그인 이후에도 미들웨어에 의해 페이지 접근이 막히는 이슈 해결
  package.json
  src/app/login/page.tsx
  src/app/mypage/settings/_components/DeleteAccountButton.tsx
  src/app/mypage/settings/_components/LogoutButton.tsx
  src/app/mypage/settings/_components/index.ts
  src/app/mypage/settings/page.tsx
  src/constants/auth.ts
  src/hooks/auth/useAuth.tsx
  src/hooks/auth/useAuth/types.ts
  src/hooks/auth/useAuth/useAuth.tsx
  src/middleware.ts
  yarn.lock
Labels: 🐞 Bug fix

#149 [DESIGN] 테스트 결과 전체 유형 UI 구현
  public/images/firstSmallResultType.png
  public/images/forthSmallResultType.png
  public/images/secondSmallResultType.png
  public/images/thirdSmallResultType.png
  src/app/test/result/_components/ResultContents.tsx
  src/app/test/result/total/page.tsx
  src/constants/index.ts
  src/constants/test/index.ts
  src/constants/test/result.tsx
Labels: 🎨 Html&css

#150 [BUGFIX] 빌드 에러 해결
  package.json
  src/app/mypage/settings/_components/DeleteAccountButton.tsx
  src/app/mypage/settings/_components/LogoutButton.tsx
  src/app/vote/page.tsx
  src/components/features/vote/voteCard/VoteCard.stories.tsx
Labels: 🐞 Bug fix

#151 [FEAT] 투표 만들기 기능
  src/app/vote/create/_components/CreateVoteForm.tsx
  src/app/vote/create/_components/VoteDateForm.tsx
  src/app/vote/create/_components/VoteItemForm.tsx
  src/app/vote/create/_components/VoteItemImgForm.tsx
  src/app/vote/create/_components/index.ts
  src/hooks/api/vote/index.ts
  src/hooks/api/vote/useCreateVoteMutation.ts
  src/hooks/index.ts
  src/hooks/useUploadImage.ts
  src/schema/CreateVoteSchema.ts
  src/utils/dates/convertNumToDay.ts
  src/utils/dates/index.ts
Labels: ✨ Feature

#153 [FEAT] 테스트 진행 완료시 API 연동 로직 구현
  src/api/test/test.ts
  src/app/test/_components/TestForm.tsx
  src/app/test/_components/TestLoading.tsx
  src/app/test/_components/TestQuestionTemplate.tsx
  src/app/test/_helper/reducer.tsx
  src/app/test/result/[id]/_components/ImageBox.tsx
  src/app/test/result/[id]/_components/KakaoScript.tsx
  src/app/test/result/[id]/_components/ResultContents.tsx
  src/app/test/result/[id]/_components/ShareBox.tsx
  src/app/test/result/[id]/_components/TempertaureBox.tsx
  src/app/test/result/[id]/_components/index.ts
  src/app/test/result/[id]/layout.tsx
  src/app/test/result/[id]/page.tsx
  src/app/test/result/total/page.tsx
  src/components/shared/kakaoShareButton/KakaoShareButton.tsx
  src/constants/category.ts
  src/constants/test/step.tsx
  src/foundations/colors/Colors.stories.tsx
  src/foundations/typography/Typography.tsx
  src/hooks/api/test/index.ts
  src/hooks/api/test/useCreateTestResult.tsx
  src/hooks/useDownloadImage.ts
  src/hooks/useLocalStorage.ts
  src/types/test/test.ts
  src/types/test/test.tsx
Labels: ✨ Feature

#154 [DESIGN] 투표 상세 페이지 UI
  src/app/vote/[slug]/_component/Replies.tsx
  src/app/vote/[slug]/_component/VoteExtraDetail.tsx
  src/app/vote/[slug]/_component/index.ts
  src/app/vote/[slug]/layout.tsx
  src/app/vote/[slug]/page.tsx
  src/components/common/divider/Divider.variant.ts
  src/components/features/vote/index.ts
  src/components/features/vote/reply/Reply.stories.tsx
  src/components/features/vote/reply/Reply.tsx
  src/components/features/vote/reply/index.ts
  src/components/features/vote/voteCard/components/Header.tsx
  src/components/features/vote/voteCard/variants.ts
  src/components/shared/index.ts
  src/components/shared/notice/Notice.tsx
  src/components/shared/profile/Profile.tsx
  src/components/shared/replyInput/ReplyInput.tsx
  styles/theme/boxShadow.ts
Labels: 🎨 Html&css

#167 [FEAT] 테스트 결과 페이지 로딩 LCP 1초에서 0.02초로 감축
  src/app/test/result/[id]/_components/ResultContents.tsx
  src/app/test/result/[id]/_components/TempertaureBox.tsx
  src/app/test/result/[id]/page.tsx
  src/contexts/reactQuery/QueryClientProvider.tsx
Labels: ✨ Feature
