Repository dnd-side-project/dnd-10th-3-frontend, pull requests merged in 2024-01, with the labels that each got.

#6 [FEAT] Avatar 인터페이스 및 스토리 구현
  src/assets/icons/user.svg
  src/components/common/avatar/Avatar.stories.tsx
  src/components/common/avatar/Avatar.tsx
  src/components/common/avatar/index.ts
Labels: ✅ Test, ✨ Feature

#8 [FEAT] 빠르게 구현 가능한 디자인 시스템 작성
  src/assets/icons/submit.svg
  src/components/common/avatar/Avatar.tsx
  src/components/common/input/Input.stories.tsx
  src/components/common/input/Input.tsx
  src/components/common/input/index.ts
  src/components/common/spinner/Spinner.stories.tsx
  src/components/common/spinner/Spinner.tsx
  src/components/common/spinner/index.ts
  src/components/common/textarea/Textarea.stories.tsx
  src/components/common/textarea/Textarea.tsx
  src/components/common/textarea/index.ts
  src/components/common/typography/Typography.stories.tsx
  src/components/common/typography/Typography.tsx
  src/components/common/typography/index.ts
  src/hooks/api/useInput.ts
  src/styles/.gitkeep
  styles/theme/borderRadius.ts
  styles/theme/boxShadow.ts
  styles/theme/colors.ts
  styles/theme/index.ts
  styles/theme/spacing.ts
  tailwind.config.ts
Labels: ✨ Feature

#41 [FEAT] Divider 컴포넌트, 스토리북
  src/components/common/divider/Divider.stories.tsx
  src/components/common/divider/Divider.tsx
  src/components/common/divider/index.ts
  src/components/common/divider/variant.tsx
Labels: ✨ Feature, 🎨 Html&css

#35 [FEAT] BottomSheet 스토리 작성
  package.json
  src/components/common/bottomSheet/BottomSheet.stories.tsx
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/common/bottomSheet/index.ts
  src/components/common/bottomSheet/style.css
  src/components/common/button/Button.tsx
  yarn.lock
Labels: ✨ Feature

#44 [FEAT] button 컴포넌트, 스토리북
  src/components/common/button/Button.stories.tsx
  src/components/common/button/Button.tsx
  src/components/common/button/index.ts
  src/components/common/button/types.ts
  src/components/common/button/variant.tsx
Labels: ✨ Feature, 🎨 Html&css

#50 [BUGFIX] eslint가 tailwind classname 순서 변경을 담당하도록 제한
  .eslintrc.json
  .prettierrc
Labels: 🐞 Bug fix

#43 [FEAT] ProgressBar 컴포넌트 및 스토리 작성
  src/components/common/progressBar/ProgressBar.stories.tsx
  src/components/common/progressBar/ProgressBar.tsx
  src/components/common/progressBar/index.ts
  src/components/common/progressBar/variant.tsx
Labels: ✨ Feature

#55 [BUGFIX] next 환경에서 SVG 컴포넌트 에러
  next.config.mjs
Labels: 🐞 Bug fix
