Repository dnd-side-project/dnd-10th-3-frontend, pull requests merged in 2024-03, with the labels that each got.

#172 [DESIGN] VoteItem 배경 색깔, VoteContent 배경 그림자 수정
  src/app/vote/_component/VoteContents.tsx
  src/components/features/vote/voteItem/VoteItem.variant.ts
  src/components/features/vote/voteItem/components/Progress.tsx
  styles/theme/boxShadow.ts
Labels: 🎨 Html&css

#173 [FEAT] 전역 에러 핸들러 (에러 바운더리)
  src/app/error.tsx
  src/app/not-found.tsx
  src/assets/images/404.svg
  src/assets/images/error.svg
  src/components/layout/fallback/Fallback.tsx
  src/components/layout/fallback/index.ts
  src/components/shared/errorHandler/ApiErrorHandler.tsx
  src/components/shared/errorHandler/NetworkErrorHandler.tsx
  src/components/shared/errorHandler/UnauthorizedErrorHandler.tsx
  src/components/shared/errorHandler/UnknownErrorHandler.tsx
  src/components/shared/errorHandler/index.ts
  src/components/shared/errorHandler/types.ts
Labels: ✨ Feature

#180 [FEAT] 투표 댓글 infinite scroll 조회 및 정렬 기능
  package.json
  src/app/vote/[slug]/_component/Replies.tsx
  src/components/common/controlTab/ControlTab.stories.tsx
  src/components/common/controlTab/ControlTab.tsx
  src/components/common/controlTab/index.ts
  src/components/features/vote/reply/Reply.stories.tsx
  src/components/features/vote/reply/Reply.tsx
  src/components/shared/endObserverList/EndObserverList.tsx
  src/components/shared/index.ts
  src/constants/options.ts
  src/hooks/vote/index.ts
  src/hooks/vote/useGetVoteReplies.ts
  src/types/response.ts
  src/types/vote/vote.ts
  yarn.lock
Labels: ✨ Feature

#181 [FEAT] 댓글 등록 기능
  package.json
  src/app/vote/[slug]/_component/Replies.tsx
  src/components/shared/endObserverList/EndObserverList.tsx
  src/components/shared/replyInput/ReplyInput.tsx
  src/components/shared/replyInput/helper/replyReducer.ts
  src/hooks/vote/index.ts
  src/hooks/vote/useCreateVoteReplyMutation.ts
  src/hooks/vote/useGetVotePaginatedReplies.ts
  src/hooks/vote/useGetVoteReplies.ts
  yarn.lock
Labels: ✨ Feature

#185 [FEAT] 댓글 삭제 기능
  src/app/vote/[slug]/_component/Replies.tsx
  src/components/common/bottomSheet/style.css
  src/components/features/vote/reply/Reply.stories.tsx
  src/components/features/vote/reply/Reply.tsx
  src/components/shared/confirmBottomSheet/ConfirmBottomSheet.tsx
  src/components/shared/index.ts
  src/components/shared/optionBottomSheet/OptionBottomSheet.tsx
  src/components/shared/replyInput/ReplyInput.tsx
  src/hooks/vote/index.ts
  src/hooks/vote/useDeleteVoteReplyMutation.ts
  src/hooks/vote/useUpdateVoteReplyMutation.ts
Labels: ✨ Feature

#186 [FEAT] 커뮤니티 검색 기능 구현
  package.json
  src/app/vote/_component/VoteContents.tsx
  src/app/vote/_component/search/SearchInput.tsx
  src/app/vote/_component/search/SearchResults.tsx
  src/app/vote/_component/search/index.ts
  src/app/vote/_component/search/variant.ts
  src/components/common/input/Input.tsx
  src/components/common/input/variant.tsx
  src/hooks/useDebounce.ts
  src/hooks/vote/index.ts
  src/hooks/vote/useGetAllVotes.tsx
  src/hooks/vote/useGetVoteBySearch.tsx
  yarn.lock
Labels: ✨ Feature

#189 [FEAT] 투표 댓글 공감 기능
  package.json
  src/app/vote/[slug]/_component/Replies.tsx
  src/app/vote/[slug]/_component/VoteDetail.tsx
  src/components/features/vote/reply/Reply.stories.tsx
  src/components/features/vote/reply/Reply.tsx
  src/components/shared/likeButton/LikeButton.tsx
  src/hooks/vote/index.ts
  src/hooks/vote/useLikeVoteMutation.ts
  src/hooks/vote/useLikeVoteReplyMutation.ts
  yarn.lock
Labels: ✨ Feature

#192 [DESIGN] 토스트 노출 위치 수정
  src/app/test/_components/TestForm.tsx
  src/app/vote/[slug]/_component/Voting.tsx
  src/components/common/toast/ToastContainer.tsx
  src/contexts/toast/ToastProvider.tsx
  src/hooks/useToast.tsx
  src/hooks/vote/useCreateVoteReplyMutation.ts
  src/hooks/vote/useDeleteVoteReplyMutation.ts
  src/hooks/vote/useLikeVoteReplyMutation.ts
  src/hooks/vote/useVotingMutation.ts
Labels: 🎨 Html&css

#193 [FEAT] 로그인된 유저 정보
  src/app/login/page.tsx
  src/app/mypage/_components/Profile.tsx
  src/app/vote/[slug]/_component/Replies.tsx
  src/app/vote/[slug]/_component/VoteDetail.tsx
  src/app/vote/[slug]/_component/VoteExtraDetail.tsx
  src/components/features/vote/reply/Reply.stories.tsx
  src/components/features/vote/reply/Reply.tsx
  src/components/shared/index.ts
  src/components/shared/redirectToPreviousPage/RedirectToPreviousPage.tsx
  src/components/shared/replyInput/ReplyInput.tsx
  src/hooks/auth/index.ts
  src/hooks/auth/types.ts
  src/hooks/auth/useAuth.tsx
  src/hooks/auth/useGetUser.ts
  src/types/user.ts
Labels: ✨ Feature

#196 [REFACTOR] svgr 라이브러리 props를 활용하여 svg 컴포넌트 크기 변경
  src/app/test/result/[id]/_components/ImageBox.tsx
  src/app/test/result/total/page.tsx
  src/assets/images/result/firstResultType.svg
  src/assets/images/result/firstSmallResultType.svg
  src/assets/images/result/forthResultType.svg
  src/assets/images/result/forthSmallResultType.svg
  src/assets/images/result/secondResultType.svg
  src/assets/images/result/secondSmallResultType.svg
  src/assets/images/result/thirdResultType.svg
  src/assets/images/result/thirdSmallResultType.svg
  src/constants/result/resultType.tsx
  src/constants/result/total.tsx
Labels: 🔨 Refactor

#197 [FEAT] 내 투표 조회 및 삭제 기능
  src/app/mypage/_components/MyVote.tsx
  src/app/vote/[slug]/_component/VoteExtraDetail.tsx
  src/app/vote/create/_components/CreateVoteForm.tsx
  src/hooks/api/vote/index.ts
  src/hooks/auth/useGetUser.ts
  src/hooks/index.ts
  src/hooks/useBottomSheetState.ts
  src/hooks/vote/index.ts
  src/hooks/vote/useCreateVoteMutation.ts
  src/hooks/vote/useDeleteVoteMutation.ts
  src/hooks/vote/useGetMyVote.ts
Labels: ✨ Feature

#198 [FEAT] 지난 테스트 조회 기능
  custom.d.ts
  src/app/mypage/_components/MyTest.tsx
  src/assets/images/result/index.ts
  src/assets/images/result/result0-domonly.svg
  src/assets/images/result/result100-domonly.svg
  src/assets/images/result/result36-domonly.svg
  src/assets/images/result/result70-domonly.svg
  src/components/features/test/resultCard/ResultCard.stories.tsx
  src/components/features/test/resultCard/ResultCard.tsx
  src/components/features/test/resultCard/index.ts
  src/hooks/test/index.ts
  src/hooks/test/useGetMyTest.ts
  tsconfig.json
Labels: ✨ Feature

#199 [FEAT] 닉네임 수정 기능
  src/app/mypage/info/_components/NicknameForm.tsx
  src/hooks/auth/index.ts
  src/hooks/auth/types.ts
  src/hooks/auth/useAuth.tsx
  src/hooks/auth/useUpdateNicknameMutation.ts
  src/schema/NicknameSchema.ts
Labels: ✨ Feature

#202 [REFACTOR] 폰트와 색깔 스토리북 MDX 파일로 리팩터링
  src/app/login/page.tsx
  src/app/mypage/_components/MyVote.tsx
  src/app/mypage/_components/Profile.tsx
  src/app/mypage/info/_components/NicknameForm.tsx
  src/app/mypage/settings/page.tsx
  src/app/not-found.tsx
  src/app/test/_components/TestForm.tsx
  src/app/test/_components/TestQuestionTemplate.tsx
  src/app/test/result/[id]/_components/ImageBox.tsx
  src/app/test/result/[id]/_components/ResultContents.tsx
  src/app/test/result/[id]/_components/ShareBox.tsx
  src/app/test/result/[id]/_components/TempertaureBox.tsx
  src/app/test/result/total/page.tsx
  src/app/vote/[slug]/_component/Replies.tsx
  src/app/vote/[slug]/_component/VoteDetail.tsx
  src/app/vote/[slug]/_component/VoteExtraDetail.tsx
  src/app/vote/_component/search/SearchResults.tsx
  src/app/vote/create/_components/CategorySelector.tsx
  src/app/vote/create/_components/CreateVoteForm.tsx
  src/app/vote/create/_components/VoteItemForm.tsx
  src/components/common/colors/Color.mdx
  src/components/common/colors/Colors.tsx
  src/components/common/colors/index.ts
  src/components/common/divider/Divider.stories.tsx
  src/components/common/icon/assets/index.ts
  src/components/common/tag/Tag.tsx
  src/components/common/toast/Toast.stories.tsx
  src/components/common/typography/Typography.mdx
  src/components/common/typography/Typography.tsx
  src/components/common/typography/index.ts
  src/components/features/test/loading/Loading.tsx
  src/components/features/test/resultCard/ResultCard.tsx
  src/components/features/vote/reply/Reply.tsx
  src/components/features/vote/voteCard/components/Description.tsx
  src/components/features/vote/voteCard/components/Footer.tsx
  src/components/features/vote/voteCard/components/Header.tsx
  src/components/layout/errors/EmptyLayout.tsx
  src/components/layout/fallback/Fallback.tsx
  src/components/layout/header/Header.tsx
  src/components/shared/confirmBottomSheet/ConfirmBottomSheet.tsx
  src/components/shared/notice/Notice.tsx
  src/components/shared/profile/Profile.tsx
  src/foundations/colors/Colors.stories.tsx
  src/foundations/typography/Typography.stories.tsx
  src/styles/theme/borderRadius.ts
  src/styles/theme/boxShadow.ts
  src/styles/theme/colors.ts
  src/styles/theme/index.ts
  src/styles/theme/spacing.ts
  tailwind.config.ts
Labels: 🔨 Refactor

#204 [REFACTOR] VoteItem 컴포넌트 리팩토링
  src/app/test/result/[id]/_components/ResultContents.tsx
  src/app/vote/[slug]/_component/Voting.tsx
  src/app/vote/_component/VoteContents.tsx
  src/app/vote/create/_components/VoteItemForm.tsx
  src/components/common/radio/Radio.variant.tsx
  src/components/features/vote/voteCard/VoteCard.stories.tsx
  src/components/features/vote/voteItem/VoteItem.stories.tsx
  src/components/features/vote/voteItem/VoteItem.tsx
  src/components/features/vote/voteItem/VoteItem.variant.ts
  src/components/features/vote/voteItem/components/IconButton.tsx
  src/components/features/vote/voteItem/components/Image.tsx
  src/components/features/vote/voteItem/components/Img.tsx
  src/components/features/vote/voteItem/components/Input.tsx
  src/components/features/vote/voteItem/components/Progress.tsx
  src/components/features/vote/voteItem/components/Text.tsx
  src/components/features/vote/voteItem/components/index.ts
Labels: 🔨 Refactor

#208 [BUGFIX] 배포 환경에 불필요한 변수 삭제
  src/constants/test/index.ts
Labels: 🐞 Bug fix

#206 [REFACTOR] 테스트 퍼널 및 로딩 로직 변경
  src/app/test/_components/TestForm.tsx
  src/app/test/_components/TestHomePage.tsx
  src/app/test/_components/TestLoading.tsx
  src/app/test/_components/TestLoadingPage.tsx
  src/app/test/_components/TestQuestionTemplate.tsx
  src/app/test/_components/TestStep.tsx
  src/app/test/_components/TestTemplate.tsx
  src/app/test/_helper/reducer.tsx
  src/app/test/page.tsx
  src/components/features/test/funnel/Funnel.stories.tsx
  src/components/features/test/funnel/Funnel.tsx
  src/components/features/test/funnel/createFunnel.ts
  src/components/features/test/loading/LoadingPage.stories.tsx
  src/components/features/test/loading/LoadingPage.tsx
  src/components/features/test/loading/index.ts
  src/constants/test/index.ts
  src/constants/test/progress.ts
  src/constants/test/step.tsx
  src/constants/test/time.ts
  src/contexts/test/TestsProvider.tsx
  src/contexts/test/useFunnelContext.tsx
  src/hooks/useFunnel.ts
  src/utils/calculate.ts
Labels: 🔨 Refactor
